chore(deps): allow google-api-core v2 on v3 release
googleapis/python-dataproc pull request #363
Opened 2022-03-10 23:33 UTC by busunkim96

Allow google-api-core<3.0.0dev on previous release of library. Note that this PR is to a new protected branch **v3**, not **main**.

This will be followed by a release PR and is a step towards removing https://github.com/googleapis/google-cloud-python/issues/10566

2022-03-13 20:19 UTC, parthea approved these changes

2022-04-01 19:02 UTC, loferris requested changes
Happy to approve after linting errors and Kokoro build passes.

2022-04-01 22:11 UTC, busunkim96 commented
@loferris Lint issues are now resolved, PTAL!

2022-04-05 17:44 UTC, loferris approved these changes

2022-04-05 17:49 UTC, merged